# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOS-Home-Exercise' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOS-Home-Exercise
  pod 'Alamofire'
  pod 'MaterialComponents/TextControls+FilledTextAreas'
  pod 'MaterialComponents/TextControls+FilledTextFields'
  pod 'MaterialComponents/Buttons'

end
